# Generated by Django 5.2.4 on 2025-08-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aios_app', '0002_remove_order_product_remove_order_quantity_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('farmer', 'farmer'), ('supplier', 'supplier'), ('admin', 'admin')], default='farmer', max_length=10),
        ),
    ]
