# Generated by Django 5.2.4 on 2025-08-11 06:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aios_app', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('farmer', 'farmer'), ('supplier', 'supplier'), ('admin', 'admin'), ('leader', 'leader'), ('agronomist', 'agronomist')], default='farmer', max_length=10),
        ),
    ]
