# Generated by Django 5.2.4 on 2025-08-12 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aios_app', '0005_alter_order_status_alter_order_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'supplier'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_supplier', to='aios_app.user'),
        ),
    ]
