# Generated by Django 5.2.4 on 2025-08-12 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aios_app', '0006_alter_order_supplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='croprecommendation',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Crop Recommendation', 'verbose_name_plural': 'Crop Recommendations'},
        ),
        migrations.AddField(
            model_name='croprecommendation',
            name='agronomist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_reviews', to='aios_app.user'),
        ),
        migrations.AddField(
            model_name='croprecommendation',
            name='agronomist_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='croprecommendation',
            name='ai_outputs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='croprecommendation',
            name='farmer_inputs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='croprecommendation',
            name='fertilizer_plan',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='croprecommendation',
            name='translated_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='croprecommendation',
            name='crop_predicted',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='croprecommendation',
            name='fertilizer_predicted',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='croprecommendation',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='croprecommendation',
            name='moisture',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='croprecommendation',
            name='nitrogen',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='croprecommendation',
            name='phosphorous',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='croprecommendation',
            name='potassium',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='croprecommendation',
            name='soil_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='croprecommendation',
            name='status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('in_review', 'In Review'), ('translated', 'Translated'), ('returned', 'Returned to Farmer')], default='pending_review', max_length=32),
        ),
        migrations.AlterField(
            model_name='croprecommendation',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='croprecommendation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crop_recommendations', to='aios_app.user'),
        ),
    ]
