# Generated by Django 5.2.4 on 2025-08-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aios_app', '0008_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='fullnames',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='farmer',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
