# Generated by Django 5.2.4 on 2025-08-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aios_app', '0009_farmer_fullnames_farmer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='fullnames',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
