# Generated by Django 5.2.4 on 2025-08-19 06:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aios_app', '0010_alter_farmer_fullnames'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(blank=True, max_length=100, null=True)),
                ('field_name', models.CharField(blank=True, max_length=100, null=True)),
                ('input_type', models.CharField(choices=[('fertilizer', 'Fertilizer'), ('pesticide', 'Pesticide'), ('seed', 'Seed')], max_length=20)),
                ('product_name', models.CharField(max_length=150)),
                ('brand', models.CharField(blank=True, max_length=150, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('l', 'liters'), ('pcs', 'pieces')], max_length=10)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('season_year', models.PositiveIntegerField()),
                ('season_name', models.CharField(max_length=30)),
                ('application_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Input usage',
                'verbose_name_plural': 'Input usages',
                'ordering': ['-application_date', '-created_at'],
                'indexes': [models.Index(fields=['farmer', 'season_year', 'season_name'], name='aios_app_us_farmer__39c586_idx'), models.Index(fields=['input_type', 'application_date'], name='aios_app_us_input_t_e3a7c5_idx')],
            },
        ),
    ]
