# Generated by Django 5.2.4 on 2025-08-21 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aios_app', '0011_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aios_app.user'),
        ),
    ]
