# Generated by Django 5.2.4 on 2025-08-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aios_app', '0012_alter_usage_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('suspended', 'suspended')], db_index=True, default='active', max_length=10),
        ),
    ]
